Replace Make_Signedbv with Make_Signedint and Make_Int
This enforces appropriate initialisation for these two types
[For I : I_Signedbv_Type, then Set_Subtype (I, Make_Nil_Type) ] for signed int
and no subtype initialisation for int.

This removes the use of 'Make_Signedbv_Type (Ireps.Empty, 32)' for an int,
and Make_Signedbv_Type (Make_Nil_Type, 32)) for a signed int.

NB If 'Make_Int_Type is replaced with 'Make_Signed_Int' type in
Add_CProver_Internal_Symbols, then the following error occurs (always in the
arrays tests):
+Error from cbmc arrays_access:
+file line 21: error: conflicting types for variable __CPROVER_rounding_mode' +old definition in module '
+int
+new definition in module `' file line 21
+signed int